src/lib.rs
=> fix(build): run rustfmt

src/parser/strings.rs
Fixes #22.
@Boddlnagg can you confirm?
=> fix(parser): replace windows newlines in ml_literal_string with \n

.travis.yml, Cargo.toml, README.md, fuzz/run.sh, src/array_of_tables.rs, src/display.rs, src/document.rs, src/formatted.rs, src/index.rs, src/lib.rs, src/parser/array.rs, src/parser/document.rs, src/parser/inline_table.rs, src/parser/strings.rs, src/parser/table.rs, src/table.rs, src/value.rs, tests/test_edit.rs, tests/test_valid.rs
=> The Grand Refactoring

README.md
=> doc(readme): add link to reordering test

src/array_of_tables.rs, src/value.rs
=> fix(len): count for tables, raw len for arrays

.travis.yml, Cargo.toml, README.md, src/decor.rs, src/display.rs, src/document.rs, src/formatted.rs, src/index.rs, src/key.rs, src/lib.rs, src/parser/array.rs, src/parser/datetime.rs, src/parser/document.rs, src/parser/errors.rs, src/parser/inline_table.rs, src/parser/key.rs, src/parser/macros.rs, src/parser/mod.rs, src/parser/numbers.rs, src/parser/strings.rs, src/parser/table.rs, src/parser/trivia.rs, src/parser/value.rs, src/table.rs, src/value.rs, tests/test_edit.rs, tests/test_parse.rs, tests/test_valid.rs
=> migrate to combine 3.3

Cargo.toml, src/table.rs
=> Document the `value` function

.travis.yml, Cargo.toml, src/decor.rs, src/display.rs, src/formatted.rs, src/index.rs, src/key.rs, src/lib.rs, src/parser/document.rs, src/parser/errors.rs, src/parser/mod.rs, src/table.rs
=> set recursion_limit to 256, bump version

.travis.yml, src/parser/document.rs, src/parser/table.rs, tests/test_parse.rs
=> travis updates

src/formatted.rs, src/index.rs, src/lib.rs, src/parser/array.rs, src/parser/datetime.rs, src/parser/inline_table.rs, src/parser/numbers.rs, src/parser/strings.rs, src/parser/table.rs, src/parser/trivia.rs, src/table.rs, src/value.rs
=> Fix for nightly

tests/test_valid.rs
=> fix(tests): fix a warning

src/decor.rs, src/formatted.rs, src/lib.rs, src/value.rs
=> Introduce decor API

Cargo.toml, src/lib.rs
=> Prepare 0.1.4

CHANGELOG.md, Cargo.toml, src/parser/datetime.rs
=> Release 0.2.0

src/lib.rs, src/table.rs
It's important api for editing table
=> Add IterMut for Table

src/parser/strings.rs
This is prep for updating the grammar to handle quotes in multi-line strings correctly.
=> style: Order string parser like ABNF

src/array.rs, src/encode.rs, src/index.rs, src/inline_table.rs, src/parser/datetime.rs, src/parser/document.rs, src/parser/value.rs, src/repr.rs, src/table.rs, src/value.rs
This is intended to help us format things correctly as we make tables
more amorphous.
=> feat: Track explicit vs implicit Decor

src/inline_table.rs, src/item.rs, src/key.rs, src/lib.rs, src/table.rs, src/value.rs, tests/test_edit.rs
There were feature disparities.  When in question, I went with mimicing
standard containers.
=> feat: Bring InlineTable up to Table

src/encode.rs
With the switch from `to_string_...` to `Display`, we can `write`
directly, rather than putting everything into a `String` and `write`ing
at the end.
=> perf: Lazily `Display` a document

src/array.rs, src/array_of_tables.rs, src/item.rs, src/key.rs, src/repr.rs, src/table.rs
This is meant to help with an API problem with implementing the standard
`Map::entry` functions.
=> feat: Support coercing Items to Values

src/inline_table.rs, src/table.rs
=> fix: Sort dotted tables

src/key.rs, src/parser/key.rs, src/parser/mod.rs, src/value.rs, tests/encoder_compliance.rs, tests/test_parse.rs
=> fix: Encode valid strings

src/encode.rs, tests/encoder_compliance.rs
A bit hacky that we aren't doing this for formatted but that'd take a bit of work, with traits just to detect this case.
=> fix: Properly serialize nan

src/value.rs, tests/test_edit.rs
Thanks toml-rs for the approach!
=> fix: Improve float output

Cargo.toml, benches/cargo.rs
Looks like we take twice as long at the moment.
=> test: Add benches

src/array.rs, src/array_of_tables.rs, src/document.rs, src/encode.rs, src/inline_table.rs, src/item.rs, src/key.rs, src/lib.rs, src/parser/array.rs, src/parser/inline_table.rs, src/parser/table.rs, src/repr.rs, src/table.rs, src/value.rs, tests/test_edit.rs, tests/test_valid.rs
This is addressing:
- Are API docs consistent?
- Do we consistently parallel stdlib?
- Do we expose all formatting for mutation?
=> fix: Clean up API

Cargo.toml, src/easy/de/array.rs, src/easy/de/array_of_tables.rs, src/easy/de/inline_table.rs, src/easy/de/item.rs, src/easy/de/mod.rs, src/easy/de/table.rs, src/easy/de/value.rs, src/easy/mod.rs, src/lib.rs
This is a step towards being a drop-in replacement for `toml-rs`
=> feat: Add serde Deserializer support

src/easy/de/array.rs, src/easy/de/inline_table.rs, src/easy/de/item.rs, src/easy/de/mod.rs, src/easy/de/table.rs, src/easy/de/table_enum.rs, src/easy/de/value.rs, tests/enum_external_deserialize.rs
Didn't realize you need `Deserializer` support for this until I came
across it in `toml-rs`.  I thought it was all in `Deserialize`.
=> fix(de): Enum support

src/parser/strings.rs
The grammar has us build strings a character-at-a-time but a small tweak
to the grammar allows us to build it in chunks of non-escaped content.
It looks like this only cut `minimal`s time by 2%
=> perf(parser): Batch create strings

examples/decode.rs
I'm cheating, this is more to help with profiling
=> docs: Add basic example

src/key.rs, src/parser/document.rs, src/parser/inline_table.rs, src/parser/mod.rs, src/repr.rs
This was done with the goal of performance but it didn't end up
improving things.  I still feel most of this makes the code somewhat
nicer, so keeping it.
=> refactor: Small cleanups

src/parser/trivia.rs
I did not measure to see if this helped performance but dfigured it was
worth doing anyways so we have less to audit.
=> refactor(parser): Remove superfluous 'attempt'

benches/cargo.rs
A lot of our overhead is in `Value`, which is less likely to be used.
Let's see the performance of what matters most.  This will also help
narrow down slow downs.
=> test(easy): Distinguish de vs Value perf

src/datetime.rs, src/easy/de/value.rs
We've been serializing datetimes as strings, making them it so on every
string, we have to try both types.  By following `toml-rs`s approach, we
remove this ambiguity and make it easier to deserialize.
This dropped decode time for `toml_edit::easy::Value` from 602us to 484us.
BREAKING CHANEG: We no longer serialize/deserialize datetimes as strings
but instead as an internal type.  To use dates, you must use
`toml_edit::Datetime`.
=> fix!: Remove serde ambiguity with Datetime

src/easy/value.rs
By default, serde checks each untagged enum's variants, to see if it works.
We can use the serde visitor to directly map types to variants.
This takes decode time for `easy::Value` from 484us to 181us, faster
than decoding directly to a native type (193us) but still slower than
native toml_edit (147us) and toml-rs (121us).
=> perf(easy): Hand-optimize `easy::Value` serde support

src/array_of_tables.rs, src/item.rs
This is to help with cargo error reporting
=> feat: All core types are Display

src/parser/document.rs, src/parser/mod.rs
=> fix: Gracefully handle BOM

src/inline_table.rs
=> fix: Sort inline table Values, not Items

src/de/inline_table.rs, src/de/mod.rs, src/de/table.rs, tests/enum_external_deserialize.rs, tests/serde.rs
=> fix(error): Report key path in de errors

src/encode.rs, src/table.rs
=> docs: Clarify table position

src/document.rs
In some cases, this makes recursive algorithms easier.  This is a
spiritual revert of part of #240.
=> feat: Re-expose Document's Item

src/index.rs, src/inline_table.rs, src/parser/errors.rs, src/table.rs, tests/fixtures/invalid/duplicate-keys-dotted.stderr
Most of this was inspired by porting cargo-edit to the latest version
=> Increase consistency

src/easy/macros.rs, src/encode.rs, src/parser/numbers.rs
=> style: Update for latest clippy

.github/workflows/audit.yml, .github/workflows/ci.yml, .github/workflows/rust-next.yml, src/easy/mod.rs
We can at least tell people our oldest supported version, even if its
always latest.
This switches to my project template for easier updating.
=> chore(ci): Check on a MSRV

.github/workflows/ci.yml, .github/workflows/rust-next.yml, crates/test-suite/tests/datetime.rs, crates/test-suite/tests/formatting.rs, crates/test-suite/tests/macros.rs, crates/test-suite/tests/parser.rs, crates/test-suite/tests/pretty.rs, crates/test-suite/tests/spanned.rs, crates/test-suite/tests/valid.rs, crates/toml/src/datetime.rs, crates/toml/src/de.rs, crates/toml/src/macros.rs, crates/toml/src/ser.rs, crates/toml/src/spanned.rs, crates/toml/src/tokens.rs, crates/toml_edit/src/de/inline_table.rs, crates/toml_edit/src/de/item.rs, crates/toml_edit/src/de/mod.rs, crates/toml_edit/src/de/table.rs, crates/toml_edit/src/de/value.rs, crates/toml_edit/src/internal_string.rs, crates/toml_edit/src/key.rs, crates/toml_edit/src/parser/macros.rs
#336 highlighted that both projects have not had clippy run in a while.  This makes it so we can re-enable clippy
=> style: Make clippy happy

crates/toml_edit/src/array.rs, crates/toml_edit/src/document.rs, crates/toml_edit/src/inline_table.rs, crates/toml_edit/src/key.rs, crates/toml_edit/src/parser/array.rs, crates/toml_edit/src/parser/datetime.rs, crates/toml_edit/src/parser/document.rs, crates/toml_edit/src/parser/inline_table.rs, crates/toml_edit/src/parser/key.rs, crates/toml_edit/src/parser/mod.rs, crates/toml_edit/src/parser/numbers.rs, crates/toml_edit/src/parser/strings.rs, crates/toml_edit/src/parser/trivia.rs, crates/toml_edit/src/parser/value.rs, crates/toml_edit/src/value.rs
This is prep for span support.
=> fix(edit)!: Be more consistent

crates/toml_edit/src/encode.rs, crates/toml_edit/src/inline_table.rs, crates/toml_edit/src/parser/inline_table.rs
=> fix(edit): Expose inline table preamble

Cargo.lock, crates/serde_spanned/src/spanned.rs, crates/toml_edit/Cargo.toml, crates/toml_edit/src/de/array.rs, crates/toml_edit/src/de/inline_table.rs, crates/toml_edit/src/de/item.rs, crates/toml_edit/src/de/key.rs, crates/toml_edit/src/de/mod.rs, crates/toml_edit/src/de/spanned.rs, crates/toml_edit/src/de/table.rs, crates/toml_edit/src/de/table_enum.rs, crates/toml_edit/src/de/value.rs, crates/toml_edit/src/easy/mod.rs, crates/toml_edit/tests/testsuite/main.rs, crates/toml_edit/tests/testsuite/spanned.rs, crates/toml_edit/tests/testsuite/spanned_impls.rs
=> feat(edit): Spanned serialization support

crates/toml_edit/tests/testsuite/invalid.rs, crates/toml_edit/tests/testsuite/main.rs
Unfortunately, #293 is still valid
Fixes #296
=> test(edit): Check specific parse errors

crates/toml_edit/src/parser/errors.rs, crates/toml_edit/src/parser/numbers.rs
PR #445 improved some error reporting but it didn't actually make it to the user because of backtracing.  Noe, we send these errors straight up.
=> fix(parser): Use more specific errors 

Cargo.lock, crates/toml/Cargo.toml, crates/toml/tests/decoder_compliance.rs, crates/toml/tests/encoder_compliance.rs, crates/toml_edit/Cargo.toml, crates/toml_edit/src/parser/state.rs, crates/toml_edit/tests/decoder_compliance.rs, crates/toml_edit/tests/easy_decoder_compliance.rs, crates/toml_edit/tests/easy_encoder_compliance.rs, crates/toml_edit/tests/encoder_compliance.rs, crates/toml_edit/tests/fixtures/invalid/encoding/bad-utf8-in-multiline-literal.stderr, crates/toml_edit/tests/fixtures/invalid/encoding/bad-utf8-in-multiline.stderr, crates/toml_edit/tests/fixtures/invalid/encoding/bad-utf8-in-string-literal.stderr, crates/toml_edit/tests/fixtures/invalid/spec/inline-table-2-0.stderr, crates/toml_edit/tests/fixtures/invalid/spec/inline-table-3-0.stderr, crates/toml_edit/tests/fixtures/invalid/spec/key-value-pair-1.stderr, crates/toml_edit/tests/fixtures/invalid/spec/keys-2.stderr, crates/toml_edit/tests/fixtures/invalid/spec/string-4-0.stderr, crates/toml_edit/tests/fixtures/invalid/spec/string-7-0.stderr, crates/toml_edit/tests/fixtures/invalid/spec/table-9-0.stderr, crates/toml_edit/tests/fixtures/invalid/spec/table-9-1.stderr, crates/toml_edit/tests/fixtures/invalid/string/bad-hex-esc-1.stderr, crates/toml_edit/tests/fixtures/invalid/string/bad-hex-esc-2.stderr, crates/toml_edit/tests/fixtures/invalid/string/bad-hex-esc-3.stderr, crates/toml_edit/tests/fixtures/invalid/string/bad-hex-esc-4.stderr, crates/toml_edit/tests/fixtures/invalid/string/bad-hex-esc-5.stderr, crates/toml_edit/tests/fixtures/invalid/string/bad-hex-esc.stderr, crates/toml_edit/tests/fixtures/invalid/table/duplicate-key-dotted-table2.stderr
=> fix(parser): Allow appending to dotted table

crates/toml/tests/testsuite/serde.rs
=> test(serde): Verify #388 was fixed by #457

crates/toml/tests/testsuite/serde.rs, crates/toml_edit/src/ser/map.rs, crates/toml_edit/src/ser/mod.rs, crates/toml_edit/src/ser/value.rs
=> fix(ser): Serialize datetimes correctly 

Cargo.lock, crates/toml_edit/Cargo.toml, crates/toml_edit/src/de/mod.rs, crates/toml_edit/src/parser/errors.rs
=> perf: Drop itertools dependency

crates/toml_edit/src/de/mod.rs, crates/toml_edit/src/de/value.rs, crates/toml_edit/src/ser/value.rs
=> docs(serde): Show how to use edit's ValueSerializer/ValueDeserializer

crates/toml/src/value.rs, crates/toml/tests/testsuite/serde.rs, crates/toml_edit/src/ser/value.rs
=> fix(serde): Newtype variant support

crates/toml_edit/src/key.rs, crates/toml_edit/tests/testsuite/parse.rs
=> fix(edit): Ensure Key::from_str doesnt rely on Document 

.github/workflows/ci.yml, .github/workflows/rust-next.yml
- ref: https://github.com/actions-rs/toolchain/issues/216
- https://github.com/dtolnay/rust-toolchain
=> Replace unmaintained Rust toolchain action

crates/toml_edit/src/item.rs, crates/toml_edit/src/key.rs, crates/toml_edit/src/parser/numbers.rs
It looks like this has little impact on performance.
Inspired by #580
=> perf: Reduce binary size

crates/toml/tests/testsuite/serde.rs, crates/toml_edit/src/ser/map.rs
=> fix(serde): Bubble up nested None errors 

crates/toml/tests/testsuite/serde.rs, crates/toml_edit/src/de/key.rs
=> fix(serde): Allow newtypes for keys

crates/toml/src/value.rs, crates/toml/tests/testsuite/float.rs, crates/toml_edit/src/ser/value.rs, crates/toml_edit/src/value.rs, crates/toml_edit/tests/testsuite/float.rs, crates/toml_edit/tests/testsuite/main.rs
As suggested in https://github.com/toml-rs/toml/pull/640#issuecomment-1783038195.
=> Serialize NaN without sign (serde only)

crates/toml/tests/testsuite/serde.rs, crates/toml_edit/src/de/table.rs
=> fix(serde): Improve spans for empty tables 

crates/toml_edit/src/key.rs
=> docs: Fix deprecation replacements

crates/toml_edit/src/error.rs, crates/toml_edit/tests/testsuite/invalid.rs
=> fix(parser): Correctly report error spans for end of string

crates/toml_edit/src/array.rs, crates/toml_edit/src/array_of_tables.rs, crates/toml_edit/src/inline_table.rs, crates/toml_edit/src/item.rs, crates/toml_edit/src/value.rs
Just a minor typo I noticed in the docs.
=> docs: fix typo

crates/toml/tests/testsuite/display.rs, crates/toml_edit/tests/testsuite/parse.rs
This is prep for #752, if we move forward with it
=> test: Various string formatting cases

crates/toml_edit/src/inline_table.rs, crates/toml_edit/src/table.rs
=> docs(edit): Clarify sort_values behavior

crates/toml/src/de/deserializer/array.rs, crates/toml/src/de/deserializer/key.rs, crates/toml/src/de/deserializer/table.rs, crates/toml/src/de/deserializer/value.rs, crates/toml_edit/src/de/array.rs, crates/toml_edit/src/de/key.rs, crates/toml_edit/src/de/table.rs
These cases were missed in #964
=> fix(edit): Fail quickly when deserializing without a span

crates/toml/src/de/parser/array.rs, crates/toml_edit/src/parser/array.rs, crates/toml_edit/tests/testsuite/edit.rs
=> fix(edit): Don't lose whitespace in empty arrays
